/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorBaseDatos;
import controller.ControladorFactura;
import controller.ControladorModeloTablas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar Beltran
 */
public class AddFactura extends javax.swing.JDialog {
    private int dataType;
    private String [] productoSeleccionado;
    private String clienteSeleccionado;
    private double subTotal = 0;
    private final double IVA = 0.19;
    private double valorTotal = 0;
    private ControladorModeloTablas controladorModeloTablas;
    
    /**
     * Creates new form AddFactura
     */
    public AddFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        productoSeleccionado = new String[15];
        controladorModeloTablas = new ControladorModeloTablas();
    }

    public AddFactura(java.awt.Frame parent, boolean modal, int dataType) {
        super(parent, modal);
        this.dataType = dataType;
        initComponents();
        productoSeleccionado = new String[15];
        controladorModeloTablas = new ControladorModeloTablas();
        setLocationRelativeTo(this);
        obtenerConsecutivo();
        cargarProductos();
        cargarClientes();
    }
    
    private int obtenerConsecutivo(){
        int nFactura;//número de la factura
        nFactura = ControladorBaseDatos.getConsecutiveNumberFactura();
        if(nFactura == 0){
            nFactura = 1;
        }
        else
            nFactura++;
        lblFactura.setText("Factura Nº "+nFactura);
        return nFactura;
    }
    
    private void cargarClientes(){
        cBoxClientes.setModel(controladorModeloTablas.fillClientesList());
    }
    
    private void cargarProductos(){
        cBoxProducto1.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto2.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto3.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto4.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto5.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto6.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto7.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto8.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto9.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto10.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto11.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto12.setModel(controladorModeloTablas.fillProductsList());
        cBoxProducto13.setModel(controladorModeloTablas.fillProductsList());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValorTotal4 = new javax.swing.JTextField();
        txtValor4 = new javax.swing.JTextField();
        txtCantidad4 = new javax.swing.JTextField();
        cBoxProducto4 = new javax.swing.JComboBox<>();
        lblFactura = new javax.swing.JLabel();
        cBoxProducto1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        txtValorTotal1 = new javax.swing.JTextField();
        txtValorTotal2 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        txtCantidad2 = new javax.swing.JTextField();
        cBoxProducto2 = new javax.swing.JComboBox<>();
        txtValorTotal3 = new javax.swing.JTextField();
        txtValor3 = new javax.swing.JTextField();
        txtCantidad3 = new javax.swing.JTextField();
        cBoxProducto3 = new javax.swing.JComboBox<>();
        txtValorTotal5 = new javax.swing.JTextField();
        txtValor5 = new javax.swing.JTextField();
        txtCantidad5 = new javax.swing.JTextField();
        cBoxProducto5 = new javax.swing.JComboBox<>();
        txtValorTotal6 = new javax.swing.JTextField();
        txtValor6 = new javax.swing.JTextField();
        txtCantidad6 = new javax.swing.JTextField();
        cBoxProducto6 = new javax.swing.JComboBox<>();
        txtValorTotal7 = new javax.swing.JTextField();
        txtValor7 = new javax.swing.JTextField();
        txtCantidad7 = new javax.swing.JTextField();
        cBoxProducto7 = new javax.swing.JComboBox<>();
        txtValorTotal8 = new javax.swing.JTextField();
        txtValor8 = new javax.swing.JTextField();
        txtCantidad8 = new javax.swing.JTextField();
        cBoxProducto8 = new javax.swing.JComboBox<>();
        txtValorTotal9 = new javax.swing.JTextField();
        txtValor9 = new javax.swing.JTextField();
        txtCantidad9 = new javax.swing.JTextField();
        cBoxProducto9 = new javax.swing.JComboBox<>();
        txtValorTotal10 = new javax.swing.JTextField();
        txtValor10 = new javax.swing.JTextField();
        txtCantidad10 = new javax.swing.JTextField();
        cBoxProducto10 = new javax.swing.JComboBox<>();
        txtValorTotal11 = new javax.swing.JTextField();
        txtValor11 = new javax.swing.JTextField();
        txtCantidad11 = new javax.swing.JTextField();
        cBoxProducto11 = new javax.swing.JComboBox<>();
        txtValorTotal12 = new javax.swing.JTextField();
        txtValor12 = new javax.swing.JTextField();
        txtCantidad12 = new javax.swing.JTextField();
        cBoxProducto12 = new javax.swing.JComboBox<>();
        txtValorTotal13 = new javax.swing.JTextField();
        txtValor13 = new javax.swing.JTextField();
        txtCantidad13 = new javax.swing.JTextField();
        cBoxProducto13 = new javax.swing.JComboBox<>();
        lblSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblIVA = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cBoxClientes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        txtValorTotal4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal4.setText("0");
        txtValorTotal4.setEnabled(false);

        txtValor4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor4.setEnabled(false);

        txtCantidad4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad4.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFactura.setText("Factura Nº");

        cBoxProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Producto");

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("Valor Unitario");

        txtValor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor1.setEnabled(false);

        lblCantidad.setText("Cantidad");

        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad1.setText("0");
        txtCantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad1FocusLost(evt);
            }
        });

        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotal.setText("Valor Total");

        txtValorTotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal1.setText("0");
        txtValorTotal1.setEnabled(false);

        txtValorTotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal2.setText("0");
        txtValorTotal2.setEnabled(false);

        txtValor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor2.setEnabled(false);

        txtCantidad2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad2.setText("0");
        txtCantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad2FocusLost(evt);
            }
        });

        cBoxProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto2ActionPerformed(evt);
            }
        });

        txtValorTotal3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal3.setText("0");
        txtValorTotal3.setEnabled(false);

        txtValor3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor3.setEnabled(false);

        txtCantidad3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad3.setText("0");
        txtCantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad3FocusLost(evt);
            }
        });

        cBoxProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto3ActionPerformed(evt);
            }
        });

        txtValorTotal5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal5.setText("0");
        txtValorTotal5.setEnabled(false);

        txtValor5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor5.setEnabled(false);

        txtCantidad5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad5.setText("0");
        txtCantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad5FocusLost(evt);
            }
        });

        cBoxProducto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto5ActionPerformed(evt);
            }
        });

        txtValorTotal6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal6.setText("0");
        txtValorTotal6.setEnabled(false);

        txtValor6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor6.setEnabled(false);

        txtCantidad6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad6.setText("0");
        txtCantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad6FocusLost(evt);
            }
        });

        cBoxProducto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto6ActionPerformed(evt);
            }
        });

        txtValorTotal7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal7.setText("0");
        txtValorTotal7.setEnabled(false);

        txtValor7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor7.setEnabled(false);

        txtCantidad7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad7.setText("0");
        txtCantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad7FocusLost(evt);
            }
        });

        cBoxProducto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto7ActionPerformed(evt);
            }
        });

        txtValorTotal8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal8.setText("0");
        txtValorTotal8.setEnabled(false);

        txtValor8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor8.setEnabled(false);

        txtCantidad8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad8.setText("0");
        txtCantidad8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad8FocusLost(evt);
            }
        });

        cBoxProducto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto8ActionPerformed(evt);
            }
        });

        txtValorTotal9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal9.setText("0");
        txtValorTotal9.setEnabled(false);

        txtValor9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor9.setEnabled(false);

        txtCantidad9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad9.setText("0");
        txtCantidad9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad9FocusLost(evt);
            }
        });

        cBoxProducto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto9ActionPerformed(evt);
            }
        });

        txtValorTotal10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal10.setText("0");
        txtValorTotal10.setEnabled(false);

        txtValor10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor10.setEnabled(false);

        txtCantidad10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad10.setText("0");
        txtCantidad10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad10FocusLost(evt);
            }
        });

        cBoxProducto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto10ActionPerformed(evt);
            }
        });

        txtValorTotal11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal11.setText("0");
        txtValorTotal11.setEnabled(false);

        txtValor11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor11.setEnabled(false);

        txtCantidad11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad11.setText("0");
        txtCantidad11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad11FocusLost(evt);
            }
        });

        cBoxProducto11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto11ActionPerformed(evt);
            }
        });

        txtValorTotal12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal12.setText("0");
        txtValorTotal12.setEnabled(false);

        txtValor12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor12.setEnabled(false);

        txtCantidad12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad12.setText("0");
        txtCantidad12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad12FocusLost(evt);
            }
        });

        cBoxProducto12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto12ActionPerformed(evt);
            }
        });

        txtValorTotal13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal13.setText("0");
        txtValorTotal13.setEnabled(false);

        txtValor13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor13.setEnabled(false);

        txtCantidad13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad13.setText("0");
        txtCantidad13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad13FocusLost(evt);
            }
        });

        cBoxProducto13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProducto13ActionPerformed(evt);
            }
        });

        lblSubTotal.setText("subTotal");

        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotal.setText("0");
        txtSubTotal.setEnabled(false);

        lblIVA.setText("I.V.A");

        txtIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVA.setText("0");
        txtIVA.setEnabled(false);

        lblTotal.setText("TOTAL");

        txtTOTAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTOTAL.setText("0");
        txtTOTAL.setEnabled(false);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        cBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxClientesActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cBoxProducto13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidad13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGenerar)
                                    .addComponent(btnCancelar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubTotal)
                                    .addComponent(lblIVA)
                                    .addComponent(lblTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorTotal13)
                                    .addComponent(txtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIVA)
                                    .addComponent(txtTOTAL)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal12)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFactura)
                                    .addComponent(cBoxProducto1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxProducto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorTotal2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                            .addComponent(txtValor1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtValorTotal1)
                                            .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                                    .addComponent(cBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFactura)
                    .addComponent(cBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblValor)
                    .addComponent(lblCantidad)
                    .addComponent(lblValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProducto13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto1ActionPerformed
        productoSeleccionado[1] = cBoxProducto1.getItemAt(cBoxProducto1.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto1ActionPerformed

    private void txtCantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad1FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[1]);
        txtValor1.setText(String.valueOf(precio));
        txtValorTotal1.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad1.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad1FocusLost

    private void txtCantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad2FocusLost
        double precio = 0;
        if(productoSeleccionado[2] != null)
            precio = controladorModeloTablas.getProductValue(productoSeleccionado[2]);
        txtValor2.setText(String.valueOf(precio));
        txtValorTotal2.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad2.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad2FocusLost

    private void txtCantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad3FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[3]);
        txtValor3.setText(String.valueOf(precio));
        txtValorTotal3.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad3.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad3FocusLost

    private void txtCantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad5FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[5]);
        txtValor5.setText(String.valueOf(precio));
        txtValorTotal5.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad5.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad5FocusLost

    private void txtCantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad6FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[6]);
        txtValor6.setText(String.valueOf(precio));
        txtValorTotal6.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad6.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad6FocusLost

    private void txtCantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad7FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[7]);
        txtValor7.setText(String.valueOf(precio));
        txtValorTotal7.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad7.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad7FocusLost

    private void txtCantidad8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad8FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[8]);
        txtValor8.setText(String.valueOf(precio));
        txtValorTotal8.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad8.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad8FocusLost

    private void txtCantidad9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad9FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[9]);
        txtValor9.setText(String.valueOf(precio));
        txtValorTotal9.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad9.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad9FocusLost

    private void txtCantidad10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad10FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[10]);
        txtValor10.setText(String.valueOf(precio));
        txtValorTotal10.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad10.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad10FocusLost

    private void txtCantidad11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad11FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[11]);
        txtValor11.setText(String.valueOf(precio));
        txtValorTotal11.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad11.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad11FocusLost

    private void txtCantidad12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad12FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[12]);
        txtValor12.setText(String.valueOf(precio));
        txtValorTotal12.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad12.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad12FocusLost

    private void txtCantidad13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad13FocusLost
        double precio = controladorModeloTablas.getProductValue(productoSeleccionado[13]);
        txtValor13.setText(String.valueOf(precio));
        txtValorTotal13.setText(String.valueOf(precio*(Integer.parseInt(txtCantidad13.getText()))));
        setSubtotal();
    }//GEN-LAST:event_txtCantidad13FocusLost

    private void cBoxProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto2ActionPerformed
        productoSeleccionado[2] = cBoxProducto2.getItemAt(cBoxProducto2.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto2ActionPerformed

    private void cBoxProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto3ActionPerformed
        productoSeleccionado[3] = cBoxProducto3.getItemAt(cBoxProducto3.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto3ActionPerformed

    private void cBoxProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto5ActionPerformed
        productoSeleccionado[5] = cBoxProducto5.getItemAt(cBoxProducto5.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto5ActionPerformed

    private void cBoxProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto6ActionPerformed
        productoSeleccionado[6] = cBoxProducto6.getItemAt(cBoxProducto6.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto6ActionPerformed

    private void cBoxProducto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto7ActionPerformed
        productoSeleccionado[7] = cBoxProducto7.getItemAt(cBoxProducto7.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto7ActionPerformed

    private void cBoxProducto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto8ActionPerformed
        productoSeleccionado[8] = cBoxProducto8.getItemAt(cBoxProducto8.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto8ActionPerformed

    private void cBoxProducto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto9ActionPerformed
        productoSeleccionado[9] = cBoxProducto9.getItemAt(cBoxProducto9.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto9ActionPerformed

    private void cBoxProducto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto10ActionPerformed
        productoSeleccionado[10] = cBoxProducto10.getItemAt(cBoxProducto10.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto10ActionPerformed

    private void cBoxProducto11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto11ActionPerformed
        productoSeleccionado[11] = cBoxProducto11.getItemAt(cBoxProducto11.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto11ActionPerformed

    private void cBoxProducto12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto12ActionPerformed
        productoSeleccionado[12] = cBoxProducto12.getItemAt(cBoxProducto12.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto12ActionPerformed

    private void cBoxProducto13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProducto13ActionPerformed
        productoSeleccionado[13] = cBoxProducto13.getItemAt(cBoxProducto13.getSelectedIndex());
    }//GEN-LAST:event_cBoxProducto13ActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if(clienteSeleccionado == null || clienteSeleccionado.equals(" "))
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente");
        else if(valorTotal == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar productos");
        }
        else{
            if (ControladorFactura.agregarFactura(obtenerConsecutivo(), controladorModeloTablas.getPersonId(clienteSeleccionado), 
                    800123321, "12/07/2019", productoSeleccionado, valorTotal))
                JOptionPane.showMessageDialog(null, "Factura generada correctamente");
         }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void cBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxClientesActionPerformed
        clienteSeleccionado = cBoxClientes.getItemAt(cBoxClientes.getSelectedIndex());
    }//GEN-LAST:event_cBoxClientesActionPerformed

    private void setSubtotal(){
        subTotal = 0;
        subTotal += Double.parseDouble(txtValorTotal1.getText());
        subTotal += Double.parseDouble(txtValorTotal2.getText());
        subTotal += Double.parseDouble(txtValorTotal3.getText());
        subTotal += Double.parseDouble(txtValorTotal5.getText());
        subTotal += Double.parseDouble(txtValorTotal6.getText());
        subTotal += Double.parseDouble(txtValorTotal7.getText());
        subTotal += Double.parseDouble(txtValorTotal8.getText());
        subTotal += Double.parseDouble(txtValorTotal9.getText());
        subTotal += Double.parseDouble(txtValorTotal10.getText());
        subTotal += Double.parseDouble(txtValorTotal11.getText());
        subTotal += Double.parseDouble(txtValorTotal12.getText());
        subTotal += Double.parseDouble(txtValorTotal13.getText());
        txtSubTotal.setText(String.valueOf(subTotal));
        txtIVA.setText(String.valueOf(subTotal*IVA));
        valorTotal = (subTotal*IVA)+subTotal;
        txtTOTAL.setText(String.valueOf(valorTotal));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cBoxClientes;
    private javax.swing.JComboBox<String> cBoxProducto1;
    private javax.swing.JComboBox<String> cBoxProducto10;
    private javax.swing.JComboBox<String> cBoxProducto11;
    private javax.swing.JComboBox<String> cBoxProducto12;
    private javax.swing.JComboBox<String> cBoxProducto13;
    private javax.swing.JComboBox<String> cBoxProducto2;
    private javax.swing.JComboBox<String> cBoxProducto3;
    private javax.swing.JComboBox<String> cBoxProducto4;
    private javax.swing.JComboBox<String> cBoxProducto5;
    private javax.swing.JComboBox<String> cBoxProducto6;
    private javax.swing.JComboBox<String> cBoxProducto7;
    private javax.swing.JComboBox<String> cBoxProducto8;
    private javax.swing.JComboBox<String> cBoxProducto9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad10;
    private javax.swing.JTextField txtCantidad11;
    private javax.swing.JTextField txtCantidad12;
    private javax.swing.JTextField txtCantidad13;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCantidad3;
    private javax.swing.JTextField txtCantidad4;
    private javax.swing.JTextField txtCantidad5;
    private javax.swing.JTextField txtCantidad6;
    private javax.swing.JTextField txtCantidad7;
    private javax.swing.JTextField txtCantidad8;
    private javax.swing.JTextField txtCantidad9;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor10;
    private javax.swing.JTextField txtValor11;
    private javax.swing.JTextField txtValor12;
    private javax.swing.JTextField txtValor13;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValor3;
    private javax.swing.JTextField txtValor4;
    private javax.swing.JTextField txtValor5;
    private javax.swing.JTextField txtValor6;
    private javax.swing.JTextField txtValor7;
    private javax.swing.JTextField txtValor8;
    private javax.swing.JTextField txtValor9;
    private javax.swing.JTextField txtValorTotal1;
    private javax.swing.JTextField txtValorTotal10;
    private javax.swing.JTextField txtValorTotal11;
    private javax.swing.JTextField txtValorTotal12;
    private javax.swing.JTextField txtValorTotal13;
    private javax.swing.JTextField txtValorTotal2;
    private javax.swing.JTextField txtValorTotal3;
    private javax.swing.JTextField txtValorTotal4;
    private javax.swing.JTextField txtValorTotal5;
    private javax.swing.JTextField txtValorTotal6;
    private javax.swing.JTextField txtValorTotal7;
    private javax.swing.JTextField txtValorTotal8;
    private javax.swing.JTextField txtValorTotal9;
    // End of variables declaration//GEN-END:variables
}
