/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorBaseDatos;

/**
 *
 * @author Omar Beltran
 */
public class Main extends javax.swing.JFrame {
    
    private ControladorBaseDatos CBD;
    /**
     * Creates new form Main
     */
    public Main() {
        CBD = new ControladorBaseDatos();
        initComponents();
        setLocationRelativeTo(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcciones = new javax.swing.JMenu();
        menuContabilidad = new javax.swing.JMenu();
        menuCGeneral = new javax.swing.JMenuItem();
        menuXFactura = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuPeopleReport = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        menuReporteFactura = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuGrabar = new javax.swing.JMenu();
        menuFactura = new javax.swing.JMenuItem();
        menuAddPerson = new javax.swing.JMenuItem();
        menuAddProduct = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE ENTRADA-SALIDA");
        setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        menuAcciones.setText("Acciones");

        menuContabilidad.setText("Contabilidad");

        menuCGeneral.setText("Generar");
        menuCGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCGeneralActionPerformed(evt);
            }
        });
        menuContabilidad.add(menuCGeneral);

        menuXFactura.setText("Una Factura");
        menuXFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuXFacturaActionPerformed(evt);
            }
        });
        menuContabilidad.add(menuXFactura);

        menuAcciones.add(menuContabilidad);

        menuReportes.setText("Reportes");

        menuPeopleReport.setText("Personas");
        menuPeopleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeopleReportActionPerformed(evt);
            }
        });
        menuReportes.add(menuPeopleReport);

        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        menuReportes.add(menuProductos);

        menuReporteFactura.setText("Facturas");
        menuReporteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteFacturaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReporteFactura);

        menuAcciones.add(menuReportes);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuAcciones.add(menuSalir);

        jMenuBar1.add(menuAcciones);

        menuGrabar.setText("Grabar");

        menuFactura.setText("Factura");
        menuFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaActionPerformed(evt);
            }
        });
        menuGrabar.add(menuFactura);

        menuAddPerson.setText("Persona");
        menuAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddPersonActionPerformed(evt);
            }
        });
        menuGrabar.add(menuAddPerson);

        menuAddProduct.setText("Producto");
        menuAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductActionPerformed(evt);
            }
        });
        menuGrabar.add(menuAddProduct);

        jMenuBar1.add(menuGrabar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddPersonActionPerformed
        new AddPerson(this, rootPaneCheckingEnabled, 2).setVisible(true);
    }//GEN-LAST:event_menuAddPersonActionPerformed

    private void menuAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductActionPerformed
         new AddProduct(this, rootPaneCheckingEnabled, 3).setVisible(true); 
    }//GEN-LAST:event_menuAddProductActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
        ShowReports showProducts = new ShowReports(this, rootPaneCheckingEnabled, 3, "");
        showProducts.setTitle("Listado de Productos");
        showProducts.setVisible(true);
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuPeopleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeopleReportActionPerformed
        ShowReports showReports = new ShowReports(this, rootPaneCheckingEnabled, 2, "");
        showReports.setTitle("Listado de Personas");
        showReports.setVisible(true);
    }//GEN-LAST:event_menuPeopleReportActionPerformed

    private void menuFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaActionPerformed
        new AddFactura(this, rootPaneCheckingEnabled, 1).setVisible(true);
    }//GEN-LAST:event_menuFacturaActionPerformed

    private void menuReporteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteFacturaActionPerformed
        ShowReports showReports = new ShowReports(this, rootPaneCheckingEnabled, 1, "");
        showReports.setTitle("Listado de Facturas");
        showReports.setVisible(true);
    }//GEN-LAST:event_menuReporteFacturaActionPerformed

    private void menuCGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCGeneralActionPerformed

    private void menuXFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuXFacturaActionPerformed
        ShowReports showProducts = new ShowReports(this, rootPaneCheckingEnabled, 4, "");
        showProducts.setTitle("Contabilidad");
        showProducts.setVisible(true);
    }//GEN-LAST:event_menuXFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenuItem menuAddPerson;
    private javax.swing.JMenuItem menuAddProduct;
    private javax.swing.JMenuItem menuCGeneral;
    private javax.swing.JMenu menuContabilidad;
    private javax.swing.JMenuItem menuFactura;
    private javax.swing.JMenu menuGrabar;
    private javax.swing.JMenuItem menuPeopleReport;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuReporteFactura;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuXFactura;
    // End of variables declaration//GEN-END:variables
}
