/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorModeloTablas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Omar Beltran
 */
public class ShowReports extends javax.swing.JDialog {
    
    private final ControladorModeloTablas CMT;
    /**
     * Creates new form ShowEmployeeByBrach
     * @param parent
     * @param modal
     * @param optReport
     */
    public ShowReports(java.awt.Frame parent, boolean modal, int optReport, String Item) {
        super(parent, modal);
        CMT = new ControladorModeloTablas();
        initComponents();
        setLocationRelativeTo(null);
        fillJTable(optReport, Item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillJTable(int optReport, String Item)
    {
        DefaultTableModel tableModel = null;
        if (optReport == 1)
            tableModel = CMT.getFacturas();
        if (optReport == 2)
            tableModel = CMT.getPersonas();
        if (optReport == 3)
            tableModel = CMT.getProductos();
        if (optReport == 4)
            tableModel = CMT.getContabilidad();
        jTable1.setModel(tableModel);      
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
